In [1]:
### Analyse du fonds Pictet ISIN CH0180951227
#### Données disponibles sur https://www.swissfunddata.ch/

In [2]:
import pandas as pd
pd.options.display.max_columns = None
pd.options.display.max_rows = None

In [5]:
df = pd.read_csv('tabula-pictet_pages-77-114.csv', header = None)

In [6]:
len(df)

1961

In [7]:
df.columns = ['Titre','Total 2020', 'Achats', 'Ventes', 'Total 2021', 'Devise','Valeur de marché', '% fortune totale comp']

In [124]:
# Check values in the 'Titre' column that are missing

df[df['Titre'].isnull()].

,Titre,Total 2020,Achats,Ventes,Total 2021,Devise,Valeur de marché,% fortune totale comp
14,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
15,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
16,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,"117,272,645.45 3.07",NaN
69,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
70,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
71,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
72,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
87,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88,NaN,NaN,NaN,NaN,NaN,NaN,"126,221,337.46 3.31",NaN
92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,NaN,NaN,NaN,NaN,NaN,NaN,0.00 0.00,NaN
115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,NaN,NaN,NaN,NaN,NaN,NaN,"21,809,556.67 0.57",NaN
125,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
126,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
127,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
128,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
180,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
181,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
182,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
183,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
206,NaN,NaN,NaN,NaN,NaN,NaN,"150,980,274.43 3.95",NaN
224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
225,NaN,NaN,NaN,NaN,NaN,NaN,"14,228,648.54 0.37",NaN
236,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
237,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
238,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
239,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
290,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
291,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
292,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
293,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
344,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
345,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
346,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
347,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
398,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
399,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
400,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
401,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
452,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
453,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
454,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
455,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
507,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
508,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
509,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
510,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
562,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
563,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
564,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
565,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
617,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
618,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
619,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
620,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
671,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
672,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
673,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
674,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
726,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
727,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
728,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
729,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
781,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
782,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
783,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
784,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
836,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
837,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
838,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
839,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
876,NaN,NaN,NaN,NaN,NaN,NaN,"450,615,624.53 11.80",NaN
880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
881,NaN,NaN,NaN,NaN,NaN,NaN,"5,320,562.77 0.14",NaN
888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
889,NaN,NaN,NaN,NaN,NaN,NaN,"6,576,323.00 0.17",NaN
890,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
891,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
892,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
893,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
945,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
946,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
947,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
948,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1000,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1001,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1002,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1003,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1036,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1037,NaN,NaN,NaN,NaN,NaN,NaN,"484,363,772.13 12.69",NaN
1043,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1044,NaN,NaN,NaN,NaN,NaN,NaN,"3,191,501.52 0.08",NaN
1054,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1055,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1056,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1057,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1061,NaN,NaN,NaN,NaN,NaN,NaN,"41,964,941.14 1.10",NaN
1065,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1066,NaN,NaN,NaN,NaN,NaN,NaN,"12,693,366.12 0.33",NaN
1075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1076,NaN,NaN,NaN,NaN,NaN,NaN,"7,985,890.23 0.21",NaN
1108,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1109,NaN,NaN,NaN,NaN,NaN,NaN,"39,787,563.13 1.04",NaN
1110,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1111,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1112,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1113,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1119,NaN,NaN,NaN,NaN,NaN,NaN,"9,164,610.90 0.24",NaN
1122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1123,NaN,NaN,NaN,NaN,NaN,NaN,"1,415,804.03 0.04",NaN
1165,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1166,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1167,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1168,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1219,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1220,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1221,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1222,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1274,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1275,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1276,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1277,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1287,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1288,NaN,NaN,NaN,NaN,NaN,NaN,"722,073,052.86 18.91",NaN
1292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1293,NaN,NaN,NaN,NaN,NaN,NaN,"566,327.11 0.01",NaN
1329,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1330,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1331,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1332,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1384,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1385,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1386,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1387,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1412,NaN,NaN,NaN,NaN,NaN,NaN,"471,192,251.36 12.34",NaN
1438,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1439,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1440,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1441,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1444,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1445,NaN,NaN,NaN,NaN,NaN,NaN,"2,821,685.15 0.07",NaN
1457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1458,NaN,NaN,NaN,NaN,NaN,NaN,"22,771,493.17 0.60",NaN
1464,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1465,NaN,NaN,NaN,NaN,NaN,NaN,"2,923,674.54 0.08",NaN
1493,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1494,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1495,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1496,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1511,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1512,NaN,NaN,NaN,NaN,NaN,NaN,"52,667,538.13 1.38",NaN
1539,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1540,NaN,NaN,NaN,NaN,NaN,NaN,"77,249,193.60 2.02",NaN
1546,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1547,NaN,NaN,NaN,NaN,NaN,NaN,0.00 0.00,NaN
1548,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1549,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1550,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1551,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1556,NaN,NaN,NaN,NaN,NaN,NaN,"10,377,563.63 0.27",NaN
1559,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1560,NaN,NaN,NaN,NaN,NaN,NaN,"980,880.00 0.03",NaN
1584,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1585,NaN,NaN,NaN,NaN,NaN,NaN,"26,963,902.92 0.71",NaN
1600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1601,NaN,NaN,NaN,NaN,NaN,NaN,"26,774,623.40 0.70",NaN
1602,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1603,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1604,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1605,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1619,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1620,NaN,NaN,NaN,NaN,NaN,NaN,"29,829,064.48 0.78",NaN
1625,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1626,NaN,NaN,NaN,NaN,NaN,NaN,"5,448,266.99 0.14",NaN
1648,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1649,NaN,NaN,NaN,NaN,NaN,NaN,"116,379,558.33 3.05",NaN
1652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1653,NaN,NaN,NaN,NaN,NaN,NaN,"842,261.82 0.02",NaN
1658,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1659,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1660,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1661,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1713,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1714,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1715,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1716,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1767,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Marktwert fortune totale du,NaN
1768,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD) compartiment /,NaN
1769,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,% des Vermögens,NaN
1770,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1822,NaN,31.12.2020 / Käufe,Verkäufe,31.12.2021 /,NaN,Währung,Marktwert fortune totale du,NaN
1823,NaN,Gesamtsumme,NaN,Gesamtsumme,NaN,NaN,(en / in USD) compartiment /,NaN
1824,NaN,zum 31.12.2020,NaN,zum 31.12.2021,NaN,NaN,% des Vermögens,NaN
1825,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1839,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1840,NaN,NaN,NaN,NaN,NaN,NaN,"63,223,435.35 1.66",NaN
1856,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1857,NaN,NaN,NaN,NaN,NaN,NaN,"8,825,097.66 0.23",NaN
1859,NaN,NaN,NaN,NaN,NaN,NaN,"3,785,348,354.41 99.16",NaN
1868,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1870,NaN,NaN,"1,511,265.20",-0.04,NaN,NaN,NaN,NaN
1873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1874,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
1877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1878,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
1883,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1884,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
1890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1891,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
1896,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1897,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
1900,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1901,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0
1904,NaN,31.12.2020 / Käufe,NaN,Verkäufe 31.12.2021 /,NaN,Währung,Marktwert fortune totale du,NaN
1905,NaN,Gesamtsumme,NaN,Gesamtsumme,NaN,NaN,(en / in USD) compartiment /,NaN
1906,NaN,zum 31.12.2020,NaN,zum 31.12.2021,NaN,NaN,% des Vermögens,NaN
1907,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1911,NaN,NaN,NaN,NaN,NaN,NaN,0.00 0.00,NaN
1916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1917,NaN,NaN,NaN,NaN,NaN,NaN,0.00 0.00,NaN
1921,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1922,NaN,NaN,NaN,NaN,NaN,NaN,0.00 0.00,NaN
1926,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1927,NaN,NaN,NaN,NaN,NaN,NaN,"74,897.42 0.00",NaN
1930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1931,NaN,NaN,NaN,NaN,NaN,NaN,0.00 0.00,NaN
1934,NaN,Käufe Währung,NaN,Verkäufe,NaN,Währung,Marktwert fortune totale du,NaN
1935,NaN,NaN,NaN,NaN,NaN,NaN,(en / in USD) compartiment /,NaN
1936,NaN,NaN,NaN,NaN,NaN,NaN,% des Vermögens,NaN
1937,NaN,NaN,NaN,NaN,NaN,NaN,des Teilvermögens,NaN
1946,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1948,NaN,31.12.2020 /,Käufe,Verkäufe,31.12.2021 /,Währung,Verpflichtung,NaN
1949,NaN,Gesamtsumme,NaN,NaN,Gesamtsumme,NaN,(en / in USD),NaN
1950,NaN,zum 31.12.2020,NaN,NaN,zum 31.12.2021,NaN,NaN,NaN

In [125]:
len(df[df['Titre'].isnull()])

245

In [126]:
df = df.dropna(subset=['Titre'])
len(df)

1716

In [127]:
df['Titre'].value_counts(ascending = False).head()

COREE DU SUD / SÜDKOREA        3
CHINE / CHINA                  3
ILES CAIMANS / KAIMANINSELN    3
INDE / INDIEN                  3
YUEXIU PROPERTY                3
Name: Titre, dtype: int64

In [128]:
df[df['Titre'] == 'COREE DU SUD / SÜDKOREA']

,Titre,Total 2020,Achats,Ventes,Total 2021,Devise,Valeur de marché,% fortune totale comp
894,COREE DU SUD / SÜDKOREA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1885,COREE DU SUD / SÜDKOREA,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1923,COREE DU SUD / SÜDKOREA,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [129]:
len(df[df['Valeur de marché'].isnull()])
# ! 'UBS AG LONDON' et 'PCH-ENHANCED LIQUIDITY USD-I DY'

62

In [130]:
df[df['Valeur de marché'].isnull()]['Titre'].value_counts()

INDE / INDIEN                                                                              3
COREE DU SUD / SÜDKOREA                                                                    3
CHINE / CHINA                                                                              3
ILES CAIMANS / KAIMANINSELN                                                                3
THAILANDE / THAILAND                                                                       2
TAIWAN / TAIWAN                                                                            2
INDONESIE / INDONESIEN                                                                     2
CHILI / CHILE                                                                              2
ARGENTINE / ARGENTINIEN                                                                    1
PAYS-BAS / NIEDERLANDE                                                                     1
LUXEMBOURG / LUXEMBURG                                                                     1
EGP                                                                                        1
HONGRIE / UNGARN                                                                           1
BRESIL / BRASILIEN                                                                         1
MEXIQUE / MEXIKO                                                                           1
EMIRATS ARABES UNIS / VEREINIGTE ARABISCHE EMIRATE                                         1
PHILIPPINES / PHILIPPINEN                                                                  1
KOWEIT / KUWAIT                                                                            1
ILES VIERGES BRITANNIQUES / BRITISCHE JUNGFERNINSELN                                       1
TOTAL AKTIEN UND ANDERE BETEILIGUNGSPAPIERE                                                1
JERSEY / JERSEY                                                                            1
OPERATIONS DE CHANGE A TERME / DEVISENTERMINGESCHÄFTE                                      1
CZK                                                                                        1
SINGAPOUR / SINGAPUR                                                                       1
GRECE / GRIECHENLAND                                                                       1
ARABIE SAOUDITE / SAUDI-ARABIEN                                                            1
TOTAL CREANCES RESULTANT D’OPERATIONS SUR DERIVES AVEC DES BROKERS /                       1
CNY                                                                                        1
VALEURS MOBILIERES NEGOCIEES SUR UN AUTRE MARCHE REGLEMENTE OUVERT AU PUBLIC /             1
RUSSIE / RUSSLAND                                                                          1
PAKISTAN / PAKISTAN                                                                        1
ILE DE MAN / ISLE OF MAN                                                                   1
COLOMBIE / KOLUMBIEN                                                                       1
EGYPTE / ÄGYPTEN                                                                           1
FUTURES / FUTURES                                                                          1
ETATS-UNIS / VEREINIGTE STAATEN                                                            1
TOTAL ACTIONS ET AUTRES TITRES DE PARTICIPATION /                                          1
MALAISIE / MALAYSIA                                                                        1
POLOGNE / POLEN                                                                            1
BERMUDES / BERMUDAS                                                                        1
QATAR / QATAR                                                                              1
UBS AG LONDON                                                                              1
OBLIGATIONS ET AUTRES TITRES DE CRÉANCE / OBLIGATIONEN UND ANDERE FORDERUNGSWERTPAPIERE    1
PEROU / PERU                                                                               1
CHYPRE / ZYPERN                                                                            1
COP                                                                                        1
TURQUIE / TÜRKEI                                                                           1
HONG KONG / HONGKONG                                                                       1
REPUBLIQUE TCHEQUE / TSCHECHISCHE REPUBLIK                                                 1
AN EINEM ANDEREN GEREGELTEN UND OFFENEN MARKT GEHANDELTE WERTPAPIERE                       1
Name: Titre, dtype: int64

In [131]:
df = df.dropna(subset=['Valeur de marché'])

### Valeur to digit

In [132]:
df.head(5)

,Titre,Total 2020,Achats,Ventes,Total 2021,Devise,Valeur de marché,% fortune totale comp
0,ABSA GROUP,"336,720",0,0,"336,720",ZAR,"3,218,460.96",0.08
1,AFRICAN RAINBOW MINERALS,"44,658","61,258","37,412","68,504",ZAR,"992,449.57",0.03
2,ANGLO AMERICAN PLATINUM,"23,470","6,352","2,899","26,923",ZAR,"3,064,718.02",0.08
3,ANGLOGOLD ASHANTI REG.,"206,588","17,368","15,220","208,736",ZAR,"4,298,967.69",0.11
4,ASPEN PHARMACARE HOLDINGS,"195,853","83,070","89,895","189,028",ZAR,"2,658,235.91",0.07

In [133]:
df['Valeur de marché'] = df['Valeur de marché'].str.replace(',','')

In [134]:
# Clean rows with bad column recognition (two numbers)

In [135]:
# Run once only #########################################################

df['Valeur de marché'] = df['Valeur de marché'].replace(' \d\.\d\d$', '', regex = True)

In [136]:
# Replace text with nan

df['Valeur de marché'] = pd.to_numeric(df['Valeur de marché'],errors='coerce')

In [138]:
df.head(5)

,Titre,Total 2020,Achats,Ventes,Total 2021,Devise,Valeur de marché,% fortune totale comp
0,ABSA GROUP,"336,720",0,0,"336,720",ZAR,3218460.96,0.08
1,AFRICAN RAINBOW MINERALS,"44,658","61,258","37,412","68,504",ZAR,992449.57,0.03
2,ANGLO AMERICAN PLATINUM,"23,470","6,352","2,899","26,923",ZAR,3064718.02,0.08
3,ANGLOGOLD ASHANTI REG.,"206,588","17,368","15,220","208,736",ZAR,4298967.69,0.11
4,ASPEN PHARMACARE HOLDINGS,"195,853","83,070","89,895","189,028",ZAR,2658235.91,0.07

In [71]:
# Define the rows to be removed
rows_to_remove = ['TOTAL OPERATIONS DE CHANGE A TERME / TOTAL DEVISENTERMINGESCHÄFTE',
                  'Titres / Titel', 
                  'Gesamtsumme', 
                  'Titres / Titel Total au',
                  'zum 31.12.2020', 
                  '31.12.2020 /','TOTAL ACTIONS ET AUTRES TITRES DE PARTICIPATION /',
                  'TOTAL DROITS / TOTAL RECHTE',
                  'FX-SW', 
                  'FX-SW 30.12.2020-16.04.2021', 
                  'FUT E-MINI MSCI EM 50 NLI 19/03/21', 
                  'FX-SW 30.12.2020-30.04.2021', 
                  'FX-SW 26.07.2021-20.08.2021', 
                  'FX-SW 06.10.2021-12.10.2021', 
                  'FUT E-MINI MSCI EM 50 NLI 18/06/21', 
                  'FUT E-MINI MSCI EM 50 NLI 17/09/21', 
                  'FUT E-MINI MSCI EM 50 NLI 17/12/21', 
                  'FUT E-MINI MSCI EM 50 NLI 18/03/22', 
                  'FX-SW 20.09.2021-14.10.2021', 
                  'FX-SW 29.12.2021-10.01.2022', 
                  'FUTURES / FUTURES']

# Use the isin method to create a boolean mask for the rows to be removed
mask = df['Titre'].isin(rows_to_remove)

df = df.drop(df[mask].index)

In [72]:
df.head(15)

,Titre,Total 2020,Achats,Ventes,Total 2021,Devise,Valeur de marché,% fortune totale comp
0,ABSA GROUP,"336,720",0,0,"336,720",ZAR,3218460.96,0.08
1,AFRICAN RAINBOW MINERALS,"44,658","61,258","37,412","68,504",ZAR,992449.57,0.03
2,ANGLO AMERICAN PLATINUM,"23,470","6,352","2,899","26,923",ZAR,3064718.02,0.08
3,ANGLOGOLD ASHANTI REG.,"206,588","17,368","15,220","208,736",ZAR,4298967.69,0.11
4,ASPEN PHARMACARE HOLDINGS,"195,853","83,070","89,895","189,028",ZAR,2658235.91,0.07
5,BID CORPORATION,"154,205",0,0,"154,205",ZAR,3153956.08,0.08
6,BIDVEST GROUP,"154,253","62,624","58,559","158,318",ZAR,1879282.31,0.05
7,CAPITEC BANK HOLDINGS,"31,285","12,366","3,760","39,891",ZAR,5098349.83,0.13
8,CLICKS GROUP,"116,195",0,0,"116,195",ZAR,2297181.01,0.06
9,DISCOVERY,"204,830","35,094","38,945","200,979",ZAR,1807929.54,0.05
10,FIRSTRAND,"2,296,943","307,780","188,657","2,416,066",ZAR,9204061.11,0.24
11,GOLD FIELDS,"436,370","32,431","35,911","432,890",ZAR,4723274.81,0.12
12,GROWTHPOINT PROPERTIES,"1,490,945","367,560",0,"1,858,505",ZAR,1789800.90,0.05
13,HARMONY GOLD MINING,"235,408",0,0,"235,408",ZAR,982341.67,0.03
18,IMPALA PLATINUM HOLDINGS,"383,142","31,508","20,881","393,769",ZAR,5551254.80,NaN

### Amazon search

In [73]:
df[df.apply(lambda row: row.astype(str).str.contains('amazon', case=False).any(), axis=1)]

Empty DataFrame
Columns: [Titre, Total 2020, Achats, Ventes, Total 2021, Devise, Valeur de marché, % fortune totale comp]
Index: []

### Tobacco search

In [74]:
df[df.apply(lambda row: row.astype(str).str.contains('tobacco', case=False).any(), axis=1)]

Empty DataFrame
Columns: [Titre, Total 2020, Achats, Ventes, Total 2021, Devise, Valeur de marché, % fortune totale comp]
Index: []

### 1. Marie's ugly people list

In [75]:
target = [
"Amazon",
#"Total",
"Toyota",
"Engie",
"Air Liquide",
"Enel",
"Iberdrola",
"Shell",
"Exxon",
"Gulf Power",
"Vinci",
"Var Energi",
"Monongahela Power Company - Mon Power",
"Monongahela",
"Philip Morris PMI",
"PMI",
"Philip Morris",
"Airbus",
"Flughafen Zurich",
"ZRH",
"Safran",
"Dassault",
"SIKA",
"Holcim",
"Danone",
"Shin-Etsu Chemical",
"Shin-Etsu",
"Pepsi",
"Bayer",
"Pernod-Ricard",
"Diageo",
"Lonza",
"Henkel",
"Walmart",
"BASF",
"Nestlé",
"Coca Cola",
"Unilever",
"Procter and Gamble",
"Procter & Gamble",
"Procter&Gamble"
"Mercedes",
"Tesla",
"Mitsubishi",
"Schneider Electric",
"ABB",
"LVMH",
"Siemens",
"Stellantis",
"Huntington Ingalls Industries Inc",
"Huntington Ingalls",
"BHP Ltd",
"EDF",
"Arcelor Mittal",
"Air Canada",
"Continental Airlines",
"Cimic group",
"Ballard Systems Power",
"Atco ltd/Canada",
"Ivanhoe Mines Ltd",
"Pan American Silver Corp",
"Lundin Mining Corp",
"Fresnillo PLC",
"Magellan Midstream Partner",
"Parkland Corp",
"Yamana Gold inc",
"Kinross Gold",
"Keyera corp",
"Delta Airlines",
"B2 Gold corp",
"AltaGas LTD",
"Heico Corp",
"SouthWest Airlines",
"Mercury NZ",
"Qantas Airways",
"Qantas",
"Diamondback Energy inc",
"Evolution mining ltd",
"Air China",
"Coal india",
"Indian oil",
"Petronas",
"Polish oil and gas company",
"Ugi corp",
"Imperial oil ltd"]

In [76]:
df_target = df[df.apply(lambda row: row.astype(str).str.contains('|'.join(target), case=False).any(), axis=1)]
len(df_target)

14

In [77]:
df_target

,Titre,Total 2020,Achats,Ventes,Total 2021,Devise,Valeur de marché,% fortune totale comp
155,ENGIE BRASIL,"108,275",0,0,"108,275",BRL,746650.41,NaN
219,ENEL AMERICAS,"15,961,868",0,"6,013,795","9,948,073",CLP,1085876.25,NaN
220,ENEL CHILE,"14,597,719",0,0,"14,597,719",CLP,510575.16,NaN
235,AIR CHINA 'A',"101,600",0,0,"101,600",CNY,145544.31,NaN
240,AIR CHINA 'H',"1,022,000",0,0,"1,022,000",HKD,713120.56,NaN
1321,COAL INDIA,"652,590",0,"652,590",0,INR,0.00,NaN
1344,HINDUSTAN UNILEVER -DEMAT.-,"398,949","33,878","32,240","400,587",INR,12718598.77,NaN
1350,INDIAN OIL -DEMATER.-,"1,029,530","222,198","230,920","1,020,808",INR,1531164.12,NaN
1390,SIEMENS (INDIA) -DEMATER.-,"124,706","62,407","90,454","96,659",INR,3070474.34,NaN
1436,UNILEVER INDONESIA,"3,422,800",0,0,"3,422,800",IDR,987047.77,NaN
1491,PETRONAS CHEMICALS GROUP,"1,031,400","176,000",0,"1,207,400",MYR,2585215.51,NaN
1492,PETRONAS DAGANGAN,"126,400","151,300","83,300","194,400",MYR,961267.39,NaN
1497,PETRONAS GAS,"397,000","91,100","90,800","397,300",MYR,1716610.63,NaN
1597,POLISH OIL AND GAS COMPANY,"925,197",0,0,"925,197",PLN,1446191.79,NaN

In [78]:
#df_target.to_clipboard()

### 2. Environnemental list

In [79]:
env = ['Albioma',
 'Alpha Metallurgical',
 'Ameren',
 'American Electric Power',
 'Arch Resources',
 'Athabasca',
 'BP p.l.c.',
 'British Petroleum',
 'Berry Corp',
 'Buzzi Unicem',
 'CF Industries',
 'Canadian Natural Resources',
 'Chevron',
 'Coronado Global Resources',
 'Denbury',
 'Electric Power Development',
 'Eni S.p.A.',
 'Eni SpA',
 'Entergy Corp',
 'Equinor',
 'Exxon',
 'HeidelbergCement',
 'Hokkaido Electric Power',
 'Hokuriku Electric Power',
 'Holcim',
 'New Hope',
 'OCI N.V.',
 'OMV AG',
 'Repsol',
 'Shell',
 'Stanmore',
 'Sumitomo Osaka Cement',
 'Taiheiyo Cement',
 'TerraCom',
 'AES Corp/The',
 'AES Corp',
 'The Scotts Miracle-Gro',
 'ScottsMiracle-Gro',
 'Southern Company',
 'TITAN COMPANY',
 'TransAlta',
 'TransAlta',
 'Vicat',
 'Vistra',
 'Soul Pattinson',
 'WHSP',
 'Yara',
 #'eREX'
]

In [80]:
df_env = df[df.apply(lambda row: row.astype(str).str.contains('|'.join(env), case=False).any(), axis=1)]

In [81]:
len(df_env)

2

In [82]:
df_env.to_clipboard()

### Airlines and airports

In [83]:
air_search = ["Aero",
"Aeroflot",
"Airline",
"Aerosvit",
"Air Berlin",
"Air China",
"Air Dolomiti",
"Air France",
"Air Namibia",
"AirAsia",
"Alitalia",
"American Airlines",
"Augsburg ",
"Austrian",
"Blue Jet",
"British Airways",
"Brussels Airlines",
"Bulgaria Air",
"Cathay",
"China Airlines",
"Delta Air Lines",
"Deutsche Bahn",
"Dragonair",
"easyJet",
"Egyptair",
"Emirates",
"Etihad",
"Far Eastern",
"Finnair",
"Germanwings",
"Hapagfly",
"Iberia",
"Jet Airways",
"JetBlue ",
"Jin Air",
"Kenya Airways",
"KLM",
"Korean Air",
"LAN Airlines",
"LTU International",
"Lufthansa",
"Malaysia Airlines",
"Niki",
"Orenburg Airlines",
"Philippine Airlines",
"Precision Air",
"Qantas",
"Qatar Airways",
"Red Wings",
"Ryanair",
"Scandinavian Airlines System",
"Shanghai Airlines",
"Shenzhen Airlines",
"SilkAir",
"Singapore Airlines",
"SmartWings",
"South African Airways",
"Southwest Airlines",
"SriLankan Airlines",
"Swiss International Air Lines",
"Swiss Air",
"TAM Brazilian Airlines",
"TAP",
"Thai Airways",
"Transaero",
"Tunisair",
"Turkish Airlines",
"United Airlines",
"US Airways",
"UTair Aviation",
"Vietnam Airlines",
"Virgin Australia",
"Vueling",
"Xiamen Airlines"]

In [84]:
air = ["AIR CHINA", 
       "SAUDI AIRLINES CATERING", 
       "CHINA SOUTHERN AIRLINES", 
       "KOREAN AIR LINES", 
       "SPRING AIRLINES",
      "INTERGLOBE AVIATION"]
# Excluding aerospace, aviation production distribution, aeronautical manufacturer, exploitation d'avions (boc aviation)

airports = ['GRUPO AEROPORTUARIO', 
           "GUANGZHOU BAIYUN INTL AIRPORT",
           "SHANGHAI INTERNATIONAL AIRPORT",
            "SHENZHEN AIRPORT",
            "MALAYSIA AIRPORTS HOLDINGS",
            "AIRPORTS OF THAILAND",
            "BEIJING CAP INTERNATIONAL AIR"
           ]

In [85]:
airport_search = ['spring']

In [86]:
df[df.apply(lambda row: row.astype(str).str.contains('|'.join(airport_search), case=False).any(), axis=1)].groupby('Titre')['Valeur de marché'].sum()

Titre
BEIJING EASPRING MAT. TECHNO. 'A'     295188.11
NONGFU SPRING 'H' 144A/S             5635810.92
SPRING AIRLINES 'A'                        0.00
Name: Valeur de marché, dtype: float64

In [87]:
df[df.apply(lambda row: row.astype(str).str.contains('|'.join(air), case=False).any(), axis=1)].groupby('Titre')['Valeur de marché'].sum()

Titre
AIR CHINA 'A'                         145544.31
AIR CHINA 'H'                         713120.56
CHINA SOUTHERN AIRLINES 'A'           315530.46
CHINA SOUTHERN AIRLINES 'H'           585826.35
INTERGLOBE AVIATION                  1319436.44
KOREAN AIR LINES                     1887516.96
KOREAN AIR LINES -NIL PAID- RIGHT          0.00
SAUDI AIRLINES CATERING                    0.00
SPRING AIRLINES 'A'                        0.00
Name: Valeur de marché, dtype: float64

In [88]:
df[df.apply(lambda row: row.astype(str).str.match('|'.join(air), case=False).any(), axis=1)].groupby('Titre')['Valeur de marché'].sum().to_clipboard()

### Oil and gas

In [89]:
oil = ['Korea National Oil Corp', 'EBN BV', 'BP Capital Markets PLC',
       'TotalEnergies Capital SA', 'ONEOK Partners LP', 'Korea Gas Corp',
       'TotalEnergies Capital International SA',
       'Shell International Finance BV', 'GS Caltex Corp',
       'Woodside Finance Ltd', 'GAS Networks Ireland',
       'Czech Gas Networks Investments Sarl', '2i Rete Gas SpA',
       'Eni SpA', 'Nederlandse Gasunie NV', 'BP Capital Markets BV',
       'SPP-Distribucia AS', 'Polski Koncern Naftowy ORLEN SA',
       'Equinor ASA', 'Kinder Morgan Inc', 'Redexis Gas Finance BV',
       'Pioneer Natural Resources Co', 'APA Infrastructure Ltd',
       'Aker BP ASA', 'Schlumberger Finance BV', 'Phillips 66',
       'Williams Cos Inc/The', 'National Fuel Gas Co',
       'East Ohio Gas Co/The', 'Boston Gas Co', 'ONEOK Inc',
       'Colonial Enterprises Inc', 'Diamondback Energy Inc',
       'Transcontinental Gas Pipe Line Co LLC',
       'Spectra Energy Partners LP',
       'Plains All American Pipeline LP / PAA Finance Corp',
       'Valero Energy Corp', 'Enterprise Products Operating LLC',
       'Suncor Energy Inc', 'Marathon Petroleum Corp',
       'EOG Resources Inc', 'Midwest Connector Capital Co LLC',
       'Northwest Pipeline LLC', 'Energy Transfer LP',
       'Atmos Energy Corp',
       'Colorado Interstate Gas Co LLC / Colorado Interstate Issuing Corp',
       'Magellan Midstream Partners LP', 'Targa Resources Corp',
       'Cenovus Energy Inc', 'MPLX LP', 'Valero Energy Partners LP',
       'NiSource Inc', 'Devon Energy Corp', 'Var Energi ASA',
       'Ovintiv Exploration Inc', 'Kinder Morgan Energy Partners LP',
       'CenterPoint Energy Resources Corp', 'Cameron International Corp',
       'Canadian Natural Resources Ltd', 'Halliburton Co', 'Enbridge Inc',
       'Florida Gas Transmission Co LLC', 'TotalEnergies SE',
       'AltaGas Ltd', 'Ampol Ltd', 'APA Group', 'APA Corp',
       'ARC Resources Ltd', 'Baker Hughes Co', 'BP PLC',
       'Brigham Minerals Inc', 'Cheniere Energy Inc', 'Chevron Corp',
       'ConocoPhillips', 'Coterra Energy Inc', 'DCC PLC', 'Enagas SA',
       'ENEOS Holdings Inc', 'EQT Corp', 'Exxon Mobil Corp',
       'Galp Energia SGPS SA', 'Hess Corp',
       'Hong Kong & China Gas Co Ltd', 'Idemitsu Kosan Co Ltd',
       'Imperial Oil Ltd', 'Inpex Corp', 'Keyera Corp',
       'Magnolia Oil & Gas Corp', 'Marathon Oil Corp',
       'Naturgy Energy Group SA', 'Neste Oyj',
       'Occidental Petroleum Corp', 'OMV AG', 'ONE Gas Inc',
       'Osaka Gas Co Ltd', 'Parkland Corp', 'Pembina Pipeline Corp',
       'Repsol SA', 'Santos Ltd', 'Schlumberger NV', 'Shell PLC',
       'Snam SpA', 'TC Energy Corp', 'Tokyo Gas Co Ltd',
       'Tourmaline Oil Corp', 'UGI Corp', 'Whiting Petroleum Corp',
       'Woodside Energy Group Ltd']

In [90]:
sorted(oil)

['2i Rete Gas SpA',
 'APA Corp',
 'APA Group',
 'APA Infrastructure Ltd',
 'ARC Resources Ltd',
 'Aker BP ASA',
 'AltaGas Ltd',
 'Ampol Ltd',
 'Atmos Energy Corp',
 'BP Capital Markets BV',
 'BP Capital Markets PLC',
 'BP PLC',
 'Baker Hughes Co',
 'Boston Gas Co',
 'Brigham Minerals Inc',
 'Cameron International Corp',
 'Canadian Natural Resources Ltd',
 'Cenovus Energy Inc',
 'CenterPoint Energy Resources Corp',
 'Cheniere Energy Inc',
 'Chevron Corp',
 'Colonial Enterprises Inc',
 'Colorado Interstate Gas Co LLC / Colorado Interstate Issuing Corp',
 'ConocoPhillips',
 'Coterra Energy Inc',
 'Czech Gas Networks Investments Sarl',
 'DCC PLC',
 'Devon Energy Corp',
 'Diamondback Energy Inc',
 'EBN BV',
 'ENEOS Holdings Inc',
 'EOG Resources Inc',
 'EQT Corp',
 'East Ohio Gas Co/The',
 'Enagas SA',
 'Enbridge Inc',
 'Energy Transfer LP',
 'Eni SpA',
 'Enterprise Products Operating LLC',
 'Equinor ASA',
 'Exxon Mobil Corp',
 'Florida Gas Transmission Co LLC',
 'GAS Networks Ireland',
 'GS Caltex Corp',
 'Galp Energia SGPS SA',
 'Halliburton Co',
 'Hess Corp',
 'Hong Kong & China Gas Co Ltd',
 'Idemitsu Kosan Co Ltd',
 'Imperial Oil Ltd',
 'Inpex Corp',
 'Keyera Corp',
 'Kinder Morgan Energy Partners LP',
 'Kinder Morgan Inc',
 'Korea Gas Corp',
 'Korea National Oil Corp',
 'MPLX LP',
 'Magellan Midstream Partners LP',
 'Magnolia Oil & Gas Corp',
 'Marathon Oil Corp',
 'Marathon Petroleum Corp',
 'Midwest Connector Capital Co LLC',
 'National Fuel Gas Co',
 'Naturgy Energy Group SA',
 'Nederlandse Gasunie NV',
 'Neste Oyj',
 'NiSource Inc',
 'Northwest Pipeline LLC',
 'OMV AG',
 'ONE Gas Inc',
 'ONEOK Inc',
 'ONEOK Partners LP',
 'Occidental Petroleum Corp',
 'Osaka Gas Co Ltd',
 'Ovintiv Exploration Inc',
 'Parkland Corp',
 'Pembina Pipeline Corp',
 'Phillips 66',
 'Pioneer Natural Resources Co',
 'Plains All American Pipeline LP / PAA Finance Corp',
 'Polski Koncern Naftowy ORLEN SA',
 'Redexis Gas Finance BV',
 'Repsol SA',
 'SPP-Distribucia AS',
 'Santos Ltd',
 'Schlumberger Finance BV',
 'Schlumberger NV',
 'Shell International Finance BV',
 'Shell PLC',
 'Snam SpA',
 'Spectra Energy Partners LP',
 'Suncor Energy Inc',
 'TC Energy Corp',
 'Targa Resources Corp',
 'Tokyo Gas Co Ltd',
 'TotalEnergies Capital International SA',
 'TotalEnergies Capital SA',
 'TotalEnergies SE',
 'Tourmaline Oil Corp',
 'Transcontinental Gas Pipe Line Co LLC',
 'UGI Corp',
 'Valero Energy Corp',
 'Valero Energy Partners LP',
 'Var Energi ASA',
 'Whiting Petroleum Corp',
 'Williams Cos Inc/The',
 'Woodside Energy Group Ltd',
 'Woodside Finance Ltd']

In [91]:
df[df.apply(lambda row: row.astype(str).str.match('|'.join(oil), case=False).any(), axis=1)]

Empty DataFrame
Columns: [Titre, Total 2020, Achats, Ventes, Total 2021, Devise, Valeur de marché, % fortune totale comp]
Index: []

In [92]:
df[df.apply(lambda row: row.astype(str).str.contains('|'.join(oil), case=False).any(), axis=1)]

Empty DataFrame
Columns: [Titre, Total 2020, Achats, Ventes, Total 2021, Devise, Valeur de marché, % fortune totale comp]
Index: []

### Mining

In [93]:
mining = ['ALUMINIUM','mine', 'mining', 'extract', "metal", 
    'BHP Group', 'Newmont', 'Rio Tinto', 'Glencore',
       'BHP Billiton', 'Caterpillar',
       'Anglo American', 'Teck Resources', 'Komatsu',
       'Rio Tinto', 'Barrick',
       'Freeport-McMoRan', 'Caterpillar',
       'Sandvik', 'Barrick', 'Sumitomo',
       'Glencore',
   'Newcrest',
       'South32', 'Franco-Nevada', 'Epiroc',
       'Agnico Eagle Mines',
       'Silfin', 'Boliden', 'Wheaton Precious Metals',
       'Norsk Hydro', 'Northern Star Resources',
       'Antofagasta', 'First Quantum Minerals',
       'Hitachi', 'Cameco',
       'Alcoa', 'Evolution Mining', 'Kinross Gold',
       'Lundin Mining', 'Pan American Silver',
       'Ivanhoe Mines',
        'BHP Group Ltd', 'Evolution Mining Ltd', 'Newcrest Mining Ltd',
       'Northern Star Resources Ltd', 'Rio Tinto Ltd', 'South32 Ltd',
       'Silfin NV', 'Agnico Eagle Mines Ltd', 'Barrick Gold Corp',
       'Cameco Corp', 'First Quantum Minerals Ltd', 'Franco-Nevada Corp',
       'Ivanhoe Mines Ltd', 'Kinross Gold Corp', 'Lundin Mining Corp',
       'Pan American Silver Corp', 'Teck Resources Ltd',
       'Wheaton Precious Metals Corp', 'Glencore Finance Europe Ltd',
       'Glencore Capital Finance DAC', 'Antofagasta PLC', 'Rio Tinto PLC',
       'Anglo American PLC', 'Glencore PLC', 'Komatsu Ltd',
       'Sumitomo Metal Mining Co Ltd',
       'Hitachi Construction Machinery Co Ltd', 'Norsk Hydro ASA',
       'Sandvik AB', 'Epiroc AB', 'Boliden AB', 'Alcoa Corp',
       'Barrick North America Finance LLC',
       'Barrick PD Australia Finance Pty Ltd', 'Caterpillar Inc',
       'Caterpillar Financial Services Corp', 'Freeport-McMoRan Inc',
       'Newmont Corp', 'BHP Billiton Finance Ltd', 'Metso Outotec Oyj']

In [94]:
sorted(mining)

['ALUMINIUM',
 'Agnico Eagle Mines',
 'Agnico Eagle Mines Ltd',
 'Alcoa',
 'Alcoa Corp',
 'Anglo American',
 'Anglo American PLC',
 'Antofagasta',
 'Antofagasta PLC',
 'BHP Billiton',
 'BHP Billiton Finance Ltd',
 'BHP Group',
 'BHP Group Ltd',
 'Barrick',
 'Barrick',
 'Barrick Gold Corp',
 'Barrick North America Finance LLC',
 'Barrick PD Australia Finance Pty Ltd',
 'Boliden',
 'Boliden AB',
 'Cameco',
 'Cameco Corp',
 'Caterpillar',
 'Caterpillar',
 'Caterpillar Financial Services Corp',
 'Caterpillar Inc',
 'Epiroc',
 'Epiroc AB',
 'Evolution Mining',
 'Evolution Mining Ltd',
 'First Quantum Minerals',
 'First Quantum Minerals Ltd',
 'Franco-Nevada',
 'Franco-Nevada Corp',
 'Freeport-McMoRan',
 'Freeport-McMoRan Inc',
 'Glencore',
 'Glencore',
 'Glencore Capital Finance DAC',
 'Glencore Finance Europe Ltd',
 'Glencore PLC',
 'Hitachi',
 'Hitachi Construction Machinery Co Ltd',
 'Ivanhoe Mines',
 'Ivanhoe Mines Ltd',
 'Kinross Gold',
 'Kinross Gold Corp',
 'Komatsu',
 'Komatsu Ltd',
 'Lundin Mining',
 'Lundin Mining Corp',
 'Metso Outotec Oyj',
 'Newcrest',
 'Newcrest Mining Ltd',
 'Newmont',
 'Newmont Corp',
 'Norsk Hydro',
 'Norsk Hydro ASA',
 'Northern Star Resources',
 'Northern Star Resources Ltd',
 'Pan American Silver',
 'Pan American Silver Corp',
 'Rio Tinto',
 'Rio Tinto',
 'Rio Tinto Ltd',
 'Rio Tinto PLC',
 'Sandvik',
 'Sandvik AB',
 'Silfin',
 'Silfin NV',
 'South32',
 'South32 Ltd',
 'Sumitomo',
 'Sumitomo Metal Mining Co Ltd',
 'Teck Resources',
 'Teck Resources Ltd',
 'Wheaton Precious Metals',
 'Wheaton Precious Metals Corp',
 'extract',
 'metal',
 'mine',
 'mining']

In [95]:
df[df.apply(lambda row: row.astype(str).str.match('|'.join(mining), case=False).any(), axis=1)]

,Titre,Total 2020,Achats,Ventes,Total 2021,Devise,Valeur de marché,% fortune totale comp
2,ANGLO AMERICAN PLATINUM,"23,470","6,352","2,899","26,923",ZAR,3064718.02,0.08
590,METALLURGICAL 'A',"656,500",0,0,"656,500",CNY,394515.65,NaN

In [96]:
df[df.apply(lambda row: row.astype(str).str.contains('|'.join(mining), case=False).any(), axis=1)]

,Titre,Total 2020,Achats,Ventes,Total 2021,Devise,Valeur de marché,% fortune totale comp
1,AFRICAN RAINBOW MINERALS,"44,658","61,258","37,412","68,504",ZAR,992449.57,0.03
2,ANGLO AMERICAN PLATINUM,"23,470","6,352","2,899","26,923",ZAR,3064718.02,0.08
13,HARMONY GOLD MINING,"235,408",0,0,"235,408",ZAR,982341.67,0.03
74,SAUDI ARABIAN MINING,"192,983","18,624",0,"211,607",SAR,4424448.54,NaN
222,SOC.QUIMICA Y MINERA PRIV. 'B',"52,322","15,721",0,"68,043",CLP,3473132.06,NaN
223,SOC.QUIMICA Y MINERA PRIV. 'B',0,"9,754","9,754",0,USD,0.00,NaN
355,CHINA MINMETALS RARE EARTH 'A',0,"48,500",0,"48,500",CNY,296933.87,NaN
590,METALLURGICAL 'A',"656,500",0,0,"656,500",CNY,394515.65,NaN
659,SHANDONG GOLD MINING 'A',"101,528",0,0,"101,528",CNY,299803.15,NaN
660,SHANDONG GOLD MINING 'H',"313,500",0,0,"313,500",HKD,536421.95,NaN
767,TONGLING NONFERROUS METALS GRP 'A',"330,900",0,0,"330,900",CNY,180678.61,NaN
831,YUNNAN ALUMINIUM 'A',0,"203,100",0,"203,100",CNY,355953.96,NaN
835,ZHAOJIN MINING INDUSTRY 'H',"619,500",0,"619,500",0,HKD,0.00,NaN
869,ZIJIN MINING GROUP 'A',"681,100","216,200","206,400","690,900",CNY,1051520.30,NaN
870,ZIJIN MINING GROUP 'H',"2,616,000","568,000","272,000","2,912,000",HKD,3466191.17,NaN
1443,POLYMETAL INTERNATIONAL,"118,274","58,156","15,182","161,248",RUB,2821685.15,NaN
1499,PRESS METAL ALUMINIUM HOLDINGS,"736,200","1,066,500","324,700","1,478,000",MYR,2050609.66,NaN

In [97]:
df[df.apply(lambda row: row.astype(str).str.contains('|'.join(mining), case=False).any(), axis=1)]['Valeur de marché'].sum()

24391403.33

### 4 affreux

Quatre entreprises sans vergogne dans la liste de Compenswiss

In [98]:
select = ['repsol', 'yara', 'cf industries', 'lundin']

df[df.apply(lambda row: row.astype(str).str.contains('|'.join(select), case=False).any(), axis=1)]

Empty DataFrame
Columns: [Titre, Total 2020, Achats, Ventes, Total 2021, Devise, Valeur de marché, % fortune totale comp]
Index: []

In [99]:
df[df.apply(lambda row: row.astype(str).str.contains('Billiton', case=False).any(), axis=1)]

Empty DataFrame
Columns: [Titre, Total 2020, Achats, Ventes, Total 2021, Devise, Valeur de marché, % fortune totale comp]
Index: []